import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const data=await fs.mkdtemp(path.join(os.tmpdir(),'schoolwork-lesson-ui-'));
const shots=path.resolve('work/lesson-verification');await fs.mkdir(shots,{recursive:true});
let app;
const results=[];
function pass(text){results.push(text);console.log('PASS:',text);}
async function launch(){return electron.launch({executablePath:process.platform==='win32'?path.resolve('node_modules/electron/dist/electron.exe'):path.resolve('node_modules/electron/dist/electron'),args:[path.resolve('scripts/test-lesson-app.cjs'),'--user-data-dir='+data,...(process.platform==='linux'?['--no-sandbox']:[])],env:{...process.env,XDG_CACHE_HOME:path.resolve('../.cache'),SCHOOLWORK_LESSON_TEST_DATA:data},timeout:30_000});}
try{
  app=await launch();app.process().stderr.on('data',chunk=>{ void fs.appendFile(path.join(shots,'electron-stderr.log'),chunk); });const page=await app.firstWindow();await page.waitForFunction(()=>Boolean(window.schoolwork));
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.getByRole('button',{name:'Settings',exact:false}).last().click();
  const select=page.getByRole('combobox',{name:'Default model'});await select.waitFor();
  await app.evaluate(()=>{global.__lessonTest.modelSaveDelay=1800;global.__lessonTest.settingsDelay=2200;});
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await select.selectOption('Meta-Llama-3.3-70B-Instruct-AWQ');assert.equal(await select.inputValue(),'Meta-Llama-3.3-70B-Instruct-AWQ');
  await select.selectOption('gpt-oss-120b-high');assert.equal(await select.inputValue(),'gpt-oss-120b-high');
  await page.waitForFunction(()=>document.querySelector('select[aria-label="Default model"]')?.value==='gpt-oss-120b-high');
  await page.waitForTimeout(4200);assert.equal(await select.inputValue(),'gpt-oss-120b-high');
  assert.equal(await page.evaluate(async()=> (await window.schoolwork.settingsGet()).model),'gpt-oss-120b-high');
  pass('model changes immediately; queued saves and stale settings cannot overwrite the latest selection');
  await app.evaluate(()=>{global.__lessonTest.modelSaveDelay=200;global.__lessonTest.settingsDelay=0;global.__lessonTest.rejectModel=true;});
  await select.selectOption('Qwen3.8-27B');await page.waitForFunction(()=>document.querySelector('select[aria-label="Default model"]')?.value==='gpt-oss-120b-high');
  await page.getByText(/Could not save model:/).first().waitFor();pass('failed model save restores the confirmed model with a visible error');
  await app.evaluate(()=>{global.__lessonTest.rejectModel=false;global.__lessonTest.modelSaveDelay=0;});
  await select.selectOption('Qwen3.8-27B');await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Follow a lesson'}).click();
  await page.getByRole('heading',{name:'Var med i lektionen.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Svenska',exact:true}).getAttribute('aria-pressed'),'true');
  await page.screenshot({path:path.join(shots,'lesson-empty.png')});
  await page.getByRole('button',{name:'Starta inspelning',exact:true}).click();await page.getByRole('button',{name:'Pausa',exact:true}).waitFor();
  await page.waitForTimeout(2000);await page.getByRole('button',{name:'Pausa',exact:true}).click();
  await page.getByText('Gör uppgift 3 nu. Lämna in rapporten den 16 oktober.',{exact:true}).waitFor({timeout:15_000});
  await page.getByRole('heading',{name:'Algebra · ekvationer'}).waitFor({timeout:15_000});
  assert.deepEqual(await app.evaluate(()=>global.__lessonTest.audioModels),['kb-whisper-large']);
  await page.locator('.lesson-title').fill('Matematik · fredag');await page.locator('.lesson-title').blur();
  await page.getByRole('button',{name:'Markera uppgift: Uppgift 3'}).click();await page.waitForFunction(()=>document.querySelector('.lesson-check')?.getAttribute('aria-pressed')==='true');
  pass('real microphone capture produces a complete WAV; Swedish Whisper, persisted transcript, structured summary and task completion work with simulated service responses');
  await page.getByRole('button',{name:'Lägg till i Calendar'}).click();
  assert.equal(await page.locator('input[type="date"]').inputValue(),'2026-10-16');assert.equal(await app.evaluate(()=>global.__lessonTest.calendarWrites),0);
  pass('assignment date is reviewed before any calendar write');
  await page.getByRole('button',{name:'Anslut Google Calendar',exact:true}).click();
  await page.getByRole('textbox',{name:'OAuth client ID',exact:true}).fill('123-test.apps.googleusercontent.com');
  await page.getByLabel('OAuth client secret',{exact:true}).fill('test-client-secret');
  await page.getByRole('button',{name:'Spara anslutningsinställningar'}).click();
  await page.getByRole('button',{name:'Logga in med Google'}).click();
  const auth=new URL(await app.evaluate(()=>global.__lessonTest.oauthUrl)),callback=new URL(auth.searchParams.get('redirect_uri'));
  callback.searchParams.set('state',auth.searchParams.get('state'));callback.searchParams.set('code','test-only-code');
  assert.equal((await fetch(callback)).status,200);await page.getByText('Konto anslutet',{exact:true}).waitFor();
  await page.locator('.calendar-dialog-layer').getByRole('button',{name:'Stäng',exact:true}).click();
  await page.getByRole('button',{name:'Bekräfta och spara'}).click();await page.getByRole('button',{name:'Sparad i Calendar'}).waitFor();
  assert.equal(await app.evaluate(()=>global.__lessonTest.calendarWrites),1);
  const calendarSession=(await page.evaluate(()=>window.schoolwork.lessonList()))[0];
  await page.evaluate(async s=>window.schoolwork.calendarAdd({id:s.id,taskId:s.analysis.tasks.find(t=>t.kind==='assignment').id,title:'Lämna in rapporten',date:'2026-10-16'}),calendarSession);
  assert.equal(await app.evaluate(()=>global.__lessonTest.calendarWrites),1);
  pass('connected Google OAuth callback, confirmed Calendar write and duplicate-event prevention work through real IPC with simulated Google responses');
  await page.getByRole('button',{name:'Kopiera text',exact:true}).click();
  await page.waitForTimeout(150);
  assert.equal(await app.evaluate(({clipboard})=>clipboard.readText()),'Gör uppgift 3 nu. Lämna in rapporten den 16 oktober.');
  pass('transcript copy writes the expected text to the clipboard');
  await page.screenshot({path:path.join(shots,'lesson-active.png')});
  const saved=await page.evaluate(()=>window.schoolwork.lessonList());assert.equal(saved[0].title,'Matematik · fredag');assert.equal(saved[0].analysis.tasks[0].completed,true);
  // Failed audio remains available for retry and does not replace an existing transcript.
  await app.evaluate(()=>{global.__lessonTest.failAudio=true;});
  await page.getByRole('button',{name:'Fortsätt',exact:true}).click();await page.waitForTimeout(1200);await page.getByRole('button',{name:'Pausa',exact:true}).click();
  await page.getByRole('button',{name:'Försök igen',exact:true}).waitFor({timeout:15_000});
  await app.evaluate(()=>{global.__lessonTest.failAudio=false;});await page.getByRole('button',{name:'Försök igen',exact:true}).click();
  await page.waitForFunction(async()=>{const s=await window.schoolwork.lessonList();return s[0].segments.length===2 && s[0].pending.length===0;});
  pass('failed audio is retained and can be retried without duplicating previous segments');
  await page.getByRole('button',{name:'English',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForTimeout(1200);await page.getByRole('button',{name:'Pause',exact:true}).click();
  await page.getByText('Do exercise three now. Submit the report on 16 October.',{exact:true}).waitFor({timeout:15_000});
  const models=await app.evaluate(()=>global.__lessonTest.audioModels);assert.equal(models.at(-1),'faster-whisper-large-v3');pass('English switch uses the multilingual Whisper model while retaining Swedish transcript segments');
  await page.getByRole('button',{name:'Transcribe',exact:true}).click();assert.equal(await page.locator('.lesson-summary').count(),0);assert.equal(await page.locator('.lesson-actions').count(),0);
  pass('ordinary transcription has its own focused layout');
  await page.getByRole('button',{name:'Svenska',exact:true}).click();
  const wav=Buffer.alloc(44+3200);wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(3200,40);
  await page.locator('input[type="file"]').setInputFiles({name:'lesson.wav',mimeType:'audio/wav',buffer:wav});
  await page.getByText('Gör uppgift 3 nu. Lämna in rapporten den 16 oktober.',{exact:true}).waitFor();
  const imported=(await page.evaluate(()=>window.schoolwork.lessonList()))[0];assert.equal(imported.mode,'transcription');assert.equal(imported.segments.length,1);assert.equal(imported.segments[0].model,'kb-whisper-large');
  pass('audio-file import uses Swedish Whisper in ordinary transcription mode');
  assert.deepEqual(errors,[]);await app.close();app=await launch();const restored=await app.firstWindow();await restored.getByRole('button',{name:'Follow a lesson'}).waitFor();await restored.getByRole('button',{name:'Follow a lesson'}).click();
  await restored.getByRole('button',{name:/^Matematik · fredag/}).click();await restored.getByText('Do exercise three now. Submit the report on 16 October.',{exact:true}).waitFor();
  assert.equal(await restored.getByRole('button',{name:'Complete task: Uppgift 3'}).getAttribute('aria-pressed'),'true');
  pass('lesson history, transcript and completed tasks survive an application restart');
  console.log(`PASS: ${results.length} lesson/model UI checks; remote TeachGPT/Google traffic simulated; real Electron IPC and microphone capture exercised.`);
}finally{await app?.close();await fs.rm(data,{recursive:true,force:true});}
